### ISSUE TITLE
the dependencies of some of the beans in the application context form a cycle:

### ISSUE THREAD

**Issue by tamzid68** [tamzid68/PassGuard#4]

**Comment by tamzid68** [comment]
The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  JWTAuthFilter defined in file [G:\game\project\PassGuard\target\classes\com\example\PassGuard\security\JWTAuthFilter.class]
↑     ↓
|  securityConfig defined in file [G:\game\project\PassGuard\target\classes\com\example\PassGuard\security\SecurityConfig.class]
└─────┘

**Comment by anisurMahmud** [comment]
Assign this issue to me. I will check it out. [Assign Process](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/assigning-issues-and-pull-requests-to-other-github-users)

**Comment by tamzid68** [comment]
solve
